services:
  - type: web
    name: chapter-03-pages-app
    env: python
    region: oregon
    plan: free
    rootDir: chapter-03-pages-app
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4